### ISSUE TITLE
Importing react-plotly causes compiling to crash

### ISSUE THREAD

**Issue by Hugo-WB** [plotly/react-plotly.js#187]
Whenever I uncomment:
`import Plot from 'react-plotly.js';`
My project  crashes
[2020-06-26T17_02_41_314Z-debug.log](https://github.com/plotly/react-plotly.js/files/4838247/2020-06-26T17_02_41_314Z-debug.log)
`
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle linear-regression-visualization@0.1.0~prestart: linear-regression-visualization@0.1.0
6 info lifecycle linear-regression-visualization@0.1.0~start: linear-regression-visualization@0.1.0
7 verbose lifecycle linear-regression-visualization@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle linear-regression-visualization@0.1.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\hugo6\Documents\Coding\ReactJS\linear-regression-visualization\node_modules\.bin;C:\Users\hugo6\anaconda3;C:\Users\hugo6\anaconda3\Library\mingw-w64\bin;C:\Users\hugo6\anaconda3\Library\usr\bin;C:\Users\hugo6\anaconda3\Library\bin;C:\Users\hugo6\anaconda3\Scripts;C:\Users\hugo6\anaconda3\bin;C:\Users\hugo6\anaconda3\condabin;C:\Program Files\PowerShell\7;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files\PowerShell\7;C:\Users\hugo6\anaconda3;C:\Users\hugo6\anaconda3\Library\mingw-w64\bin;C:\Users\hugo6\anaconda3\Library\usr\bin;C:\Users\hugo6\anaconda3\Library\bin;C:\Users\hugo6\anaconda3\Scripts;C:\Users\hugo6\Documents\Coding\Python3.8.3\Scripts;C:\Users\hugo6\Documents\Coding\Python3.8.3;C:\Users\hugo6\AppData\Local\Microsoft\WindowsApps;C:\Users\hugo6\AppData\Roaming\npm;C:\Users\hugo6\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\hugo6\AppData\Local\atom\bin;C:\Program Files (x86)\GitHub CLI;C:\Octave\Octave-5.2.0\mingw64\bin;C:\Users\hugo6\AppData\Local\Pandoc;C:\Users\hugo6\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64
9 verbose lifecycle linear-regression-visualization@0.1.0~start: CWD: C:\Users\hugo6\Documents\Coding\ReactJS\linear-regression-visualization
10 silly lifecycle linear-regression-visualization@0.1.0~start: Args: [ '/d /s /c', 'react-scripts start' ]
11 silly lifecycle linear-regression-visualization@0.1.0~start: Returned: code: 134  signal: null
12 info lifecycle linear-regression-visualization@0.1.0~start: Failed to exec start script
13 verbose stack Error: linear-regression-visualization@0.1.0 start: `react-scripts start`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid linear-regression-visualization@0.1.0
15 verbose cwd C:\Users\hugo6\Documents\Coding\ReactJS\linear-regression-visualization
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 134
22 error linear-regression-visualization@0.1.0 start: `react-scripts start`
22 error Exit status 134
23 error Failed at the linear-regression-visualization@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]

`

` "plotly.js": "^1.54.5",
"react-plotly.js": "^2.4.0",`

I am genuinely so confused, would love some help. 
I'll try using the CDNs for now.
Than kyou

**Comment by Hugo-WB** [comment]
Never mind I fixed it by importing everything separately.
As done by the user here:
https://community.plotly.com/t/react-plotly-not-working-with-create-react-app-update/36297
guess i need more RAM :(
